### PR TITLE
Pull request for issue #1

### PR DESCRIPTION
**Pull request by altenhof**

### CODE REVIEW

**Review by crewjam — CHANGES_REQUESTED** [review]
looks like .gitignore got in here by accident, otherwise  LGTM

**Comment by altenhof** [comment]
Well, I added it to avoid uploads of my IntelliJ project files, but I removed it again as you've requested

Best

Michael

**Comment by altenhof** [comment]
Hi @crewjam,

should be fine now, shouldn't it?

BTW Your repo is lacking a license file. Would be great if you added one. APL preferred :-)

Best

Michael

**Review by crewjam — APPROVED** [review]

**Comment by crewjam** [comment]
Yes, all set. Thanks for your contribution!

**Pull request merged**
